export const GET_POKELIST = `GET_POKELIST`
export const GET_POKELIST_SUCCESS = `GET_POKELIST_SUCCESS`
export const GET_POKELIST_FAILED = `GET_POKELIST_FAILED`

export const GET_POKEMON_DETAIL = `GET_POKEMON_DETAIL`
export const GET_POKEMON_DETAIL_SUCCESS = `GET_POKEMON_DETAIL_SUCCESS`
export const GET_POKEMON_DETAIL_FAILED = `GET_POKEMON_DETAIL_FAILED`

export const GET_POKEMON_BEFORE = `GET_POKEMON_BEFORE`
export const GET_POKEMON_BEFORE_SUCCESS = `GET_POKEMON_BEFORE_SUCCESS`
export const GET_POKEMON_BEFORE_FAILED = `GET_POKEMON_BEFORE_FAILED`

export const GET_POKEMON_AFTER = `GET_POKEMON_AFTER`
export const GET_POKEMON_AFTER_SUCCESS = `GET_POKEMON_AFTER_SUCCESS`
export const GET_POKEMON_AFTER_FAILED = `GET_POKEMON_AFTER_FAILED`

export const GET_POKEMON_DETAIL_PAGE = `GET_POKEMON_DETAIL_PAGE`
export const GET_POKEMON_DETAIL_PAGE_SUCCESS = `GET_POKEMON_DETAIL_PAGE_SUCCESS`
export const GET_POKEMON_DETAIL_PAGE_FAILED = `GET_POKEMON_DETAIL_PAGE_FAILED`
